### ISSUE TITLE
(3471,P4) Links not aligned fr switching a course between classes

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release16UAT#1]
As links have had read-only appended to the end, they have become mis-aligned and the text has dropped down the page and overlays a pipe character that is used to separate the links

Steps To Reproduce	
1 - Login as student with a course in several classes, course has links for switching between classes, links are aligned at the bottom of each course listing
2 - Click on links to move course around classes
3 - Read-only is appended to links
4 - Links become mis-aligned
![link-not-aligned 2](https://cloud.githubusercontent.com/assets/7794513/6282816/ce6a5f2c-b900-11e4-9270-e4b8d6809319.PNG)

**Comment by dharamveerSanodiya** [comment]
Hi Rahul,
UI changes done for this issue. Please check and let me know.
Cheers,
Dharam

**Comment by rahul-kumar11** [comment]
retested and passed on UAT
