### ISSUE TITLE
(3567,P4) Font shows small when selecting Terms and Conditions when access code added on behalf of

### ISSUE THREAD

**Issue by besiddharth** [subrata1106/Release16UAT#10]
When a user is activated on a course by a Teacher Admin or higher using Bulk Import, when the user logs in they must accept the Terms and Conditions when they first launch the course

 The Terms and Conditions text is in a smaller font than the rest of the lightbox
1 - login as Teacher Admin or above
 2 - add an access code for a new course for a user using bulk import
 3 - logout
 4 - login as user
 5 - click on course name or graphic to launch, lightbox appears to accept Terms and Conditions

![terms-and-conditions-on-behalf-of](https://cloud.githubusercontent.com/assets/9006565/6592876/cb3a0360-c7ca-11e4-9979-54ea737b4e05.png)

**Comment by dharamveerSanodiya** [comment]
Font size of the given font is resized and available in QA+UAT.

**Comment by rahul-kumar11** [comment]
passed on UAT
