### ISSUE TITLE
(3561,P4) User details are not aligned in boxes

### ISSUE THREAD

**Issue by besiddharth** [subrata1106/Release16UAT#11]
When in Manage users, click on Show details to view which courses and classes the student is linked with

Table of details is not aligned and shows cells at the top mis-aligned with the rest
1 - login as org admin
 2 - click on Manage users
 3 - Select a user and click Show details
 4 - borders of cells not aligned in user details

![user-details-not-aligned](https://cloud.githubusercontent.com/assets/9006565/6592955/5697c38e-c7cb-11e4-8dc2-b1c218d36be0.PNG)

**Comment by dharamveerSanodiya** [comment]
Bug resolved and available in QA+ UAT.

**Comment by rahul-kumar11** [comment]
passed on UAT
