### ISSUE TITLE
(3603,P4) Layout of lightbox when licence has expired

### ISSUE THREAD

**Issue by besiddharth** [subrata1106/Release16UAT#16]
When a licence has expired and the user attempts to launch for the first time, they get a lightbox message that the licence has expired and an option to Renew or to Access as read-only.

I would suggest a line break between the message 'Your licence has expired' and 'To continue using the course, renew your licence'

**Comment by dharamveerSanodiya** [comment]
Code is checked in and available in QA+UAT.

**Comment by rahul-kumar11** [comment]
passed on UAT
