### ISSUE TITLE
(3604,P4) Layout of lightbox when renewing licence

### ISSUE THREAD

**Issue by besiddharth** [subrata1106/Release16UAT#17]
When a licence has expired and the user attempts to launch for the first time, they get a lightbox message that the licence has expired and an option to Renew or to Access as read-only

 When they click on Renew licence they come to a new lightbox, Renew licence

 I would suggest a line break between the message 'If you have an access code, enter it here. This could be in your book, or purchased online.' and 'Access code help'

**Comment by dharamveerSanodiya** [comment]
Suggestion implemented for renew licence pop-up. Solution is checked in n avilable in QA+UAT.

**Comment by rahul-kumar11** [comment]
passed on UAT
