### ISSUE TITLE
(3565,P3) Content missing in notiifcation when course is renewed on behalf of

### ISSUE THREAD

**Issue by besiddharth** [subrata1106/Release16UAT#19]
When a course is renewed on behalf of a user (i.e. using bulk import), the whole content of the message is not shown

 The sentence 'Your .' is shown instead of showing the validity period:

 'You licence is valid for XXXX (validity period)

![activation-notification](https://cloud.githubusercontent.com/assets/9006565/6595904/00c4474a-c7e7-11e4-8abd-5499d6a96ad0.PNG)

**Comment by besiddharth** [comment]
The code has been fixed for the same.

**Comment by rahul-kumar11** [comment]
retested and passed on UAT
