### ISSUE TITLE
(3496, P3) Should spelling be 'license' or 'licence'?

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release16UAT#2]
When a user's licence has expired to a product and they have links and lightbox option to renew, licence has two spellings:
- licence
- license
One spelling should be used for consistency, in the requirements document the spelling used is 'licence'

Steps To Reproduce	
1 - Login as user with expired courses
2 - 'Licence' is expired message shows next to course listing
3 - Click on course to launch
4 - Lightbox shows a mixture of 'licence' and 'license'
![license-or-licence](https://cloud.githubusercontent.com/assets/7794513/6283534/e66dd5f8-b90b-11e4-9bd5-5db9dd0d8123.PNG)

**Comment by vanrajsinh-parmar** [comment]
Language pack changes done. Please retest the issue.

**Comment by rahul-kumar11** [comment]
retested and passed in UAT
