### ISSUE TITLE
(3574,P3) When user is removed from a course goes to hidden courses instead of to self-study

### ISSUE THREAD

**Issue by besiddharth** [subrata1106/Release16UAT#20]
If a user has activated a course and the licence is active, if the teacher removes them from the class, it is expected that the course becomes self-study and remains active

 Instead, the course is moved to hidden courses and the student must click on 'View hidden'. There is no option to access the course as self-study, only to access a read-only course in the previous class.

 Relates to TestLink Test Case 1059 - https://oup-testlink.ttp.io/index.php [^]

1 - login as student and activate a course in a class
 2 - login as teacher and remove student from class
 3 - login as student, expect to be able to access course as self-study, but course is put under Hidden and can only access a read-only copy from previous class

![sol-shows-in-hidden](https://cloud.githubusercontent.com/assets/9006565/6595952/63f451e8-c7e7-11e4-8a64-153292e6b5a3.PNG)

**Comment by rahul-kumar11** [comment]
passed on UAT
