### ISSUE TITLE
(3396,P4)  Incorrect language in text box indicating length of licence

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release16UAT#4]
Please note an 's' is missing when a licence is set to 18 months. See screenshot for more info.
![18month](https://cloud.githubusercontent.com/assets/7794513/6286573/fe53c70e-b92e-11e4-8acc-f8f5cc5183ae.jpg)

**Comment by vanrajsinh-parmar** [comment]
Code fixed. Please retest.

**Comment by rahul-kumar11** [comment]
retested and passed and resolved on UAT
