### ISSUE TITLE
(3552,P3)Editing the User Admin filed as PDP administrator creates 2 issues

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release16UAT#5]
Hello,
PDP admin can make the user id invisible by doing this:

1. Login as PDP admin.
2. C.ick on "Manage Organization".
3 Click on "Set up additional fields to help you manage your users".

Then then they can make the field invisible but if thsi happens the issues explained in tickets 3495/3500 occur.

TCS to investigate is this can be fixed on this release.

Thanks

Tony

**Comment by besiddharth** [comment]
The issue has been fixed.

**Comment by rahul-kumar11** [comment]
passed on UAT
