### ISSUE TITLE
(3548,P4) Teacher notification of expiry needs a line break

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release16UAT#6]
Please add a line break between 'Best wishes' and 'Customer Support' for teacher notification of pending expiry of students' licences so it matches the student one

**Comment by besiddharth** [comment]
This is resolved and was part of 27-Feb-2015 UAT build. Also, verified by user and closed the issue.

**Comment by rahul-kumar11** [comment]
passed on UAT
