### ISSUE TITLE
 (3547,P3) Notification not received when 6 months remaining on licence

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/Release16UAT#7]
A notification has not been received although only 6 months remain on the licence

The licence has a 6 month duration, so the notification would be expected after activation

User has logged out and logged back in twice, notification not received

XML document does include this milestone for this licence duration

1 - validate access code with 6 month duration
2 - launch course to activate licence
3 - return to My home page
4 - course listing shows as active and validity period shows as 6 months
5 - go to My notifications, no message is received that 6 months left on licence

**Comment by besiddharth** [comment]
The issue is happening due to different data coming from EAC in expiry date format where the response the data is valid however it is coming out in one of the different format in every request which is not expected.

**Comment by rahul-kumar11** [comment]
passed on UAT
