### ISSUE TITLE
(3560,P4) Cannot view Business activity

### ISSUE THREAD

**Issue by besiddharth** [subrata1106/Release16UAT#8]
Cannot view Business activity for org admin user, receive error page

1 - login as org admin
 2 - click on Business activity in left hand panel
 3 - error page shows

![error-page-business-activity](https://cloud.githubusercontent.com/assets/9006565/6444576/60fc8692-c0f6-11e4-9174-c92e87522645.PNG)

**Comment by besiddharth** [comment]
This is resolved and was part of 27-Feb-2015 UAT build. Also, verified by user and closed the issue.

**Comment by rahul-kumar11** [comment]
passed on UAT
